
CREATE TABLE Worker(
  WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME CHAR(25),
  LAST_NAME CHAR(25),
  SALARY INT(15),
  JOINING_DATE DATE,
  DEPARTMENT CHAR(25)
);


INSERT INTO Worker
  (FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPARTMENT) VALUES
  
  ('MONIKA','AHUJA',100000,'14-02-20','HR'),
  ('Niharika','Verma',80000,'14-06-11','Admin'),
	('Vishal','Singhal',300000,'14-02-20','HR'),
	('Amitabh','Singh',500000,'14-02-20','Admin'),
	('Vivek','Bhati',500000,'14-06-11','Admin'),
	('Vipul','Diwan',200000,'14-06-11','Account'),
	('Satish','Kumar',75000,'14-01-20','Account'),
	('Geetika','Chauhan',90000,'14-04-11','Admin');

CREATE TABLE Bonus(
  WORKER_REF_ID INT,
  BONUS_AMOUNT INT(10),
  BONUS_DATE DATE,
  FOREIGN KEY (WORKER_REF_ID)
    REFERENCES Worker(WORKER_ID)
  ON DELETE CASCADE
);

INSERT INTO Bonus
  (WORKER_REF_ID,BONUS_AMOUNT,BONUS_DATE) VALUES
  
  (1,5000,'16-02-20'),
  (2,3000,'16-06-11'),
	(3,4000,'16-02-20'),
	(1,4500,'16-02-20'),
	(2,3500,'16-06-11');
	
CREATE TABLE Title(
  WORKER_REF_ID INT,
  WORKER_TITLE CHAR(25),
  AFFECTED_FROM DATE,
  FOREIGN KEY(WORKER_REF_ID)
    references Worker(WORKER_ID)
  ON DELETE CASCADE
);

INSERT INTO Title
  (WORKER_REF_ID,WORKER_TITLE,AFFECTED_FROM) VALUES
  
  (1,'Manager','2017-05-25'),
  (2,'Executive','2016-06-11'),
  (8,'Executive','2016-06-11 '),
  (5,'Manager','2016-06-11'),
  (4,'Asst. Manager','2016-06-11'),
  (7,'Executive','2016-06-11'),
  (6,'Lead','2016-06-11'),
  (3,'Lead','2016-06-11');


SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;

SELECT DISTINCT(DEPARTMENT) FROM WORKER;

SELECT FIRST_NAME,LAST_NAME FROM WORKER WHERE SALARY>100000;

SELECT FIRST_NAME,LAST_NAME FROM WORKER WHERE SALARY<100000 AND DEPARTMENT='Admin';

SELECT * FROM WORKER WHERE DEPARTMENT='Admin' OR DEPARTMENT='Account';

SELECT * FROM WORKER ORDER BY SALARY desc;

UPDATE WORKER SET SALARY=80000 where WORKER_ID=7;

SELECT * FROM WORKER;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS 'NAME' FROM WORKER;

SELECT * FROM WORKER WHERE FIRST_NAME IN('Monika','Satish');

SELECT * FROM WORKER WHERE FIRST_NAME LIKE '%a';

SELECT * FROM WORKER WHERE SALARY BETWEEN 200000 AND 500000;

SELECT * FROM WORKER WHERE year(JOINING_DATE)='2014' AND month(JOINING_DATE)='6';

SELECT DEPARTMENT,COUNT(WORKER_ID) AS NO_OF_WORKERS
FROM WORKER
GROUP BY DEPARTMENT
ORDER BY NO_OF_WORKERS DESC;

SELECT DISTINCT W.FIRST_NAME,T.WORKER_TITLE
FROM WORKER W 
INNER JOIN Title T
ON W.WORKER_ID=T.WORKER_REF_ID
AND T.WORKER_TITLE='Manager';

SELECT WORKER_TITLE,AFFECTED_FROM,COUNT(*)
FROM Title
GROUP BY WORKER_TITLE,AFFECTED_FROM
HAVING COUNT(*)>1;


SELECT W.WORKER_ID,W.FIRST_NAME,W.SALARY
FROM WORKER W,WORKER W1
WHERE W.SALARY=W1.SALARY
AND W.WORKER_ID!=W1.WORKER_ID
ORDER BY W.WORKER_ID ASC;

INSERT INTO WORKER 
  (FIRST_NAME,LAST_NAME,SALARY,JOINING_DATE,DEPARTMENT) VALUES
  ("Karan","Rohra",90000,'14-05-20','HR');
  
DELETE FROM WORKER WHERE FIRST_NAME='Karan';

SELECT DISTINCT SALARY FROM WORKER ORDER BY SALARY DESC LIMIT 3;


CREATE VIEW DEPARTMENT_INFO AS
SELECT max(SALARY) AS MAXIMUM_SALARY,DEPARTMENT
FROM WORKER
GROUP BY DEPARTMENT;

SELECT * FROM DEPARTMENT_INFO;

ALTER TABLE Bonus
RENAME COLUMN BONUS_AMOUNT to AMOUNT;

delimiter //
CREATE PROCEDURE DISPLAY_DEPARTMENT(DEPT char(25))
BEGIN
SELECT * FROM WORKER WHERE DEPARTMENT=DEPT;
END //
delimiter ;

CALL DISPLAY_DEPARTMENT('Admin');

